version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  automerged_updates:
    - match:
        dependency_type: all
        update_type: all
