name = "Noknok"
license = "MIT"
licenselink = "https://github.com/opera7133/noknok/blob/master/LICENSE"
description = "A lean and mean theme for your portfolio."
homepage = "https://github.com/opera7133/noknok"
tags = ["Hugo", "minimal", "Tailwind CSS", "theme", "portfolio", "Light", "Dark", "Projects", "simple", "clean", "personal", "Blog"]
features = ["portfolio"]
min_version = "0.69"

[author]
  name = "wamo"
  homepage = "https://wmsci.com"
