baseURL = "https://example.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "Noknok"
theme = "noknok"

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "G-1234567890"

[params]
# The number of articles to be displayed on a single page.
paginator_pages = "5"

  [params.site]
    name = "Noknok"

  [params.homepage_meta_tags]
    meta_description = "A lean and mean theme for your portfolio."
    meta_og_title = "Noknok"
    meta_og_type = "website"
    meta_og_url = "https://example.com"
    meta_og_image = "https://example.com/img/thumbnail.png"
    meta_og_description = "A lean and mean theme for your portfolio."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@scgame_m"
    meta_twitter_creator = "@scgame_m"

  [params.main]
    username = "noknok"
    description = "A lean and mean theme for your portfolio."
    image = "https://i.imgur.com/SAe92bt.png"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "works"
    name = "Works"
    url = "/works/"
    weight = 3

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 4

  [[menu.ex]]
    name = "Contact"
    url = "/contact"
      weight = 1

[build]
  writeStats = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true

# If you're using Yandex.Metrica, you can enable this feature.
#[params.analytics.yandexmetrica]
#    enabled = true
#    tagNumber = ''